### ISSUE TITLE
Link to the catalog in the online tutorial

### ISSUE THREAD

**Issue by gysel** [ServiceCutter/ServiceCutter#13]
The online tutorial should have a prominent hyperlink to the coupling criteria catalog/reference.

**Comment by gysel** [comment]
What should it reference? The wiki? https://github.com/ServiceCutter/ServiceCutter/wiki/Coupling-Criteria

**Comment by socadk** [comment]
Yes, the wiki is a good reference. BTW, it would be nice to convert the cards into markdown/HTML tables (to ease future evolution and maintenance).
