### ISSUE TITLE
Build Issue - failed dependency for grunt-karma

### ISSUE THREAD

**Issue by omallassi** [ServiceCutter/ServiceCutter#24]
all, 

Just to let you know I was facing build issue for the Editor 
running 

``mvn spring-boot:run -Drun.jvmArguments='-Dserver.port=8080``

ended up with 

```
[INFO] --------------------------------------
[INFO]          NPM INSTALL
[INFO] --------------------------------------
npm WARN npm npm does not support Node.js v8.11.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: editor@0.0.0
npm ERR! Found: karma@1.7.1
npm ERR! node_modules/karma
npm ERR!   dev karma@"1.7.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer karma@"~0.12.0" from grunt-karma@0.11.0
npm ERR! node_modules/grunt-karma
npm ERR!   dev grunt-karma@"0.11.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Obviously same with docker. 

As a work around I updated package.json to 

``"grunt-karma": "1.0.0",``

this is clearly a work around as the build generates dozen of WARN but.... 

cannot promise but will see if I can have more proper updates of depdencies.

**Comment by gysel** [comment]
Thanks for letting me know! 

I don't really plan to fix any build problems going forward. But I have published working Docker images into the GitHub Container Registry.

You should be able to run the application using the updated [docker-compose.yml](https://github.com/ServiceCutter/ServiceCutter/blob/master/docker-compose.yml) file.
