### ISSUE TITLE
Replace User Representations upon re-upload

### ISSUE THREAD

**Issue by gysel** [ServiceCutter/ServiceCutter#5]
As a service cutting architect, I would like to overwrite (fully replace) an existing user representation with a new JSON file with new constraints etc.

**Comment by gysel** [comment]
**Current behavior**
Error when uploading user reps for a second time: "Enhancing an already specified system is not yet implemented!"

**Suggested new behavior**
The new user reps replace the existing ones.

**Comment by gysel** [comment]
@olzzio / @koelbener do you agree with this solution?

If so, I'll merge it to master.

**Comment by koelbener** [comment]
@gysel: The code or the approach? approach seems fine to me

**Comment by gysel** [comment]
The approach. ;)

(The code should be acceptable... ;))

**Comment by gysel** [comment]
merged
